<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DesktopServices\DesktopServices.csproj" />
    <ProjectReference Include="..\HD_AccesoDatos\HD_AccesoDatos.csproj" />
    <ProjectReference Include="..\HD_Administracion\HD_Administracion.csproj" />
    <ProjectReference Include="..\HD_Auditoria\HD_Auditoria.csproj" />
    <ProjectReference Include="..\HD_Buro\HD_Buro.csproj" />
    <ProjectReference Include="..\HD_Clientes\HD_Clientes.csproj" />
    <ProjectReference Include="..\HD_Cobranza\HD_Cobranza.csproj" />
    <ProjectReference Include="..\HD_Dashboard\HD_Dashboard.csproj" />
    <ProjectReference Include="..\HD_Finanzas\HD_Finanzas.csproj" />
    <ProjectReference Include="..\HD_Fiscal\HD_Fiscal.csproj" />
    <ProjectReference Include="..\HD_Generales\HD_Generales.csproj" />
    <ProjectReference Include="..\HD_GestionActividades\HD_GestionActividades.csproj" />
    <ProjectReference Include="..\HD_Helpers\HD_Helpers.csproj" />
    <ProjectReference Include="..\HD_Mensajeria\HD_Mensajeria.csproj" />
    <ProjectReference Include="..\HD_Notifications\HD_Notifications.csproj" />
    <ProjectReference Include="..\HD_RedesSociales\HD_RedesSociales.csproj" />
    <ProjectReference Include="..\HD_Reporteria\HD_Reporteria.csproj" />
    <ProjectReference Include="..\HD_Security\HD_Security.csproj" />
    <ProjectReference Include="..\HD_Ventas\HD_Ventas.csproj" />
    <ProjectReference Include="..\Postventa\Postventa.csproj" />
    <ProjectReference Include="..\ProductoAliado\ProductoAliado.csproj" />
    <ProjectReference Include="..\Teletrabajo\Teletrabajo.csproj" />
    <ProjectReference Include="..\Usados\Usados.csproj" />
    <ProjectReference Include="..\Ventas\Ventas.csproj" />
  </ItemGroup>

</Project>
